source activate tf36
python /home/andi/Documents/kinematics_continuum_robot/forward_kinematics.py --save_data 1 --num_poses 45000
python /home/andi/Documents/kinematics_continuum_robot/forward_kinematics.py --save_data 1 --num_poses 50000
python /home/andi/Documents/kinematics_continuum_robot/forward_kinematics.py --save_data 1 --num_poses 55000
python /home/andi/Documents/kinematics_continuum_robot/forward_kinematics.py --save_data 1 --num_poses 60000
python /home/andi/Documents/kinematics_continuum_robot/forward_kinematics.py --save_data 1 --num_poses 65000
python /home/andi/Documents/kinematics_continuum_robot/forward_kinematics.py --save_data 1 --num_poses 70000
python /home/andi/Documents/kinematics_continuum_robot/forward_kinematics.py --save_data 1 --num_poses 75000
python /home/andi/Documents/kinematics_continuum_robot/forward_kinematics.py --save_data 1 --num_poses 80000
python /home/andi/Documents/kinematics_continuum_robot/forward_kinematics.py --save_data 1 --num_poses 85000
python /home/andi/Documents/kinematics_continuum_robot/forward_kinematics.py --save_data 1 --num_poses 90000
python /home/andi/Documents/kinematics_continuum_robot/forward_kinematics.py --save_data 1 --num_poses 95000
python /home/andi/Documents/kinematics_continuum_robot/forward_kinematics.py --save_data 1 --num_poses 100000
python /home/andi/Documents/kinematics_continuum_robot/forward_kinematics.py --save_data 1 --num_poses 105000
python /home/andi/Documents/kinematics_continuum_robot/forward_kinematics.py --save_data 1 --num_poses 110000
python /home/andi/Documents/kinematics_continuum_robot/forward_kinematics.py --save_data 1 --num_poses 115000
python /home/andi/Documents/kinematics_continuum_robot/forward_kinematics.py --save_data 1 --num_poses 120000
python /home/andi/Documents/kinematics_continuum_robot/forward_kinematics.py --save_data 1 --num_poses 125000
python /home/andi/Documents/kinematics_continuum_robot/forward_kinematics.py --save_data 1 --num_poses 130000
python /home/andi/Documents/kinematics_continuum_robot/forward_kinematics.py --save_data 1 --num_poses 135000
python /home/andi/Documents/kinematics_continuum_robot/forward_kinematics.py --save_data 1 --num_poses 140000
python /home/andi/Documents/kinematics_continuum_robot/forward_kinematics.py --save_data 1 --num_poses 145000
python /home/andi/Documents/kinematics_continuum_robot/forward_kinematics.py --save_data 1 --num_poses 150000
python /home/andi/Documents/kinematics_continuum_robot/forward_kinematics.py --save_data 1 --num_poses 155000
python /home/andi/Documents/kinematics_continuum_robot/forward_kinematics.py --save_data 1 --num_poses 160000
python /home/andi/Documents/kinematics_continuum_robot/forward_kinematics.py --save_data 1 --num_poses 165000
python /home/andi/Documents/kinematics_continuum_robot/forward_kinematics.py --save_data 1 --num_poses 170000
python /home/andi/Documents/kinematics_continuum_robot/forward_kinematics.py --save_data 1 --num_poses 175000
python /home/andi/Documents/kinematics_continuum_robot/forward_kinematics.py --save_data 1 --num_poses 180000
python /home/andi/Documents/kinematics_continuum_robot/forward_kinematics.py --save_data 1 --num_poses 185000
python /home/andi/Documents/kinematics_continuum_robot/forward_kinematics.py --save_data 1 --num_poses 190000
python /home/andi/Documents/kinematics_continuum_robot/forward_kinematics.py --save_data 1 --num_poses 195000
python /home/andi/Documents/kinematics_continuum_robot/forward_kinematics.py --save_data 1 --num_poses 200000
python /home/andi/Documents/kinematics_continuum_robot/forward_kinematics.py --save_data 1 --num_poses 205000
python /home/andi/Documents/kinematics_continuum_robot/forward_kinematics.py --save_data 1 --num_poses 210000
python /home/andi/Documents/kinematics_continuum_robot/forward_kinematics.py --save_data 1 --num_poses 215000
python /home/andi/Documents/kinematics_continuum_robot/forward_kinematics.py --save_data 1 --num_poses 220000
python /home/andi/Documents/kinematics_continuum_robot/forward_kinematics.py --save_data 1 --num_poses 225000
python /home/andi/Documents/kinematics_continuum_robot/forward_kinematics.py --save_data 1 --num_poses 230000
python /home/andi/Documents/kinematics_continuum_robot/forward_kinematics.py --save_data 1 --num_poses 235000
python /home/andi/Documents/kinematics_continuum_robot/forward_kinematics.py --save_data 1 --num_poses 240000
python /home/andi/Documents/kinematics_continuum_robot/forward_kinematics.py --save_data 1 --num_poses 245000
python /home/andi/Documents/kinematics_continuum_robot/forward_kinematics.py --save_data 1 --num_poses 250000
python /home/andi/Documents/kinematics_continuum_robot/forward_kinematics.py --save_data 1 --num_poses 255000
python /home/andi/Documents/kinematics_continuum_robot/forward_kinematics.py --save_data 1 --num_poses 260000
python /home/andi/Documents/kinematics_continuum_robot/forward_kinematics.py --save_data 1 --num_poses 265000
python /home/andi/Documents/kinematics_continuum_robot/forward_kinematics.py --save_data 1 --num_poses 270000
python /home/andi/Documents/kinematics_continuum_robot/forward_kinematics.py --save_data 1 --num_poses 275000
python /home/andi/Documents/kinematics_continuum_robot/forward_kinematics.py --save_data 1 --num_poses 280000
python /home/andi/Documents/kinematics_continuum_robot/forward_kinematics.py --save_data 1 --num_poses 285000
python /home/andi/Documents/kinematics_continuum_robot/forward_kinematics.py --save_data 1 --num_poses 290000
python /home/andi/Documents/kinematics_continuum_robot/forward_kinematics.py --save_data 1 --num_poses 295000
python /home/andi/Documents/kinematics_continuum_robot/forward_kinematics.py --save_data 1 --num_poses 300000
python /home/andi/Documents/kinematics_continuum_robot/forward_kinematics.py --save_data 1 --num_poses 305000
python /home/andi/Documents/kinematics_continuum_robot/forward_kinematics.py --save_data 1 --num_poses 310000
python /home/andi/Documents/kinematics_continuum_robot/forward_kinematics.py --save_data 1 --num_poses 315000
python /home/andi/Documents/kinematics_continuum_robot/forward_kinematics.py --save_data 1 --num_poses 320000
python /home/andi/Documents/kinematics_continuum_robot/forward_kinematics.py --save_data 1 --num_poses 325000
python /home/andi/Documents/kinematics_continuum_robot/forward_kinematics.py --save_data 1 --num_poses 330000
python /home/andi/Documents/kinematics_continuum_robot/forward_kinematics.py --save_data 1 --num_poses 335000
python /home/andi/Documents/kinematics_continuum_robot/forward_kinematics.py --save_data 1 --num_poses 340000
python /home/andi/Documents/kinematics_continuum_robot/forward_kinematics.py --save_data 1 --num_poses 345000
python /home/andi/Documents/kinematics_continuum_robot/forward_kinematics.py --save_data 1 --num_poses 350000
python /home/andi/Documents/kinematics_continuum_robot/forward_kinematics.py --save_data 1 --num_poses 355000
